//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by AppRes.rc
//
#define IDR_MENU1                       101
#define IDD_PROP_DEFAULTS               102
#define IDR_ACCELERATOR1                103
#define IDI_ICON1                       104
#define IDI_ICON2                       105
#define IDD_ABOUTDLG                    106
#define IDR_TOOLBAR_BITMAP              107
#define IDD_REPEATDLG                   108
#define IDD_PROP_STYLE                  109
#define IDD_PROP_FONT                   110
#define IDD_PROP_ALARM                  111
#define IDD_ALARMDLG                    112
#define IDD_PROP_DIR                    113
#define IDD_PROP_ACTION                 114
#define IDD_JUMPDLG                     115
#define IDD_RANGEDLG                    116
#define IDD_FINDDLG                     117
#define IDD_PROP_TODO                   118
#define IDD_PROP_PRIVATE                119
#define IDD_IMPORTDLG                   120
#define IDD_SYNCDLG                     121
#define IDD_PROP_COLOR                  122
#define IDS_LEFTBUTTON                  132
#define IDS_RIGHTBUTTON                 133
#define IDR_MENUBAR1                    134
#define IDR_MENUBAR2                    135
#define IDM_MAIN_MENU                   400
#define IDR_MENU2                       401
#define IDC_VERSION                     1000
#define IDC_DAILY                       1001
#define IDC_WEEKLY                      1002
#define IDC_MONTHLY                     1003
#define IDC_YEARLY                      1004
#define IDC_BYDAY                       1005
#define IDC_NONE                        1006
#define IDC_FREQ                        1007
#define IDC_STARTDATE                   1008
#define IDC_ENDDATE                     1009
#define IDC_DATE                        1010
#define IDC_1ST                         1011
#define IDC_2ND                         1012
#define IDC_3RD                         1013
#define IDC_4TH                         1014
#define IDC_5TH                         1015
#define IDC_MON                         1016
#define IDC_TUE                         1017
#define IDC_WED                         1018
#define IDC_THU                         1019
#define IDC_FRI                         1020
#define IDC_SAT                         1021
#define IDC_SUN                         1022
#define IDC_JAN                         1023
#define IDC_FEB                         1024
#define IDC_MAR                         1025
#define IDC_APL                         1026
#define IDC_MAY                         1027
#define IDC_JUN                         1028
#define IDC_JUL                         1029
#define IDC_AUG                         1030
#define IDC_SEP                         1031
#define IDC_OCT                         1032
#define IDC_NOV                         1033
#define IDC_FREQTEXT                    1034
#define IDC_12H                         1035
#define IDC_24H                         1036
#define IDC_CASH                        1037
#define IDC_BACKGROUND                  1038
#define IDC_ALLHOUR                     1039
#define IDC_APPONLY                     1040
#define IDC_FIRSTHOUR                   1041
#define IDC_LASTHOUR                    1042
#define IDC_GRAPH                       1043
#define IDC_DURATION                    1044
#define IDC_ENABLE                      1045
#define IDC_LEADTIME                    1046
#define IDC_MONTHVIEW                   1047
#define IDC_WEEKVIEW                    1048
#define IDC_WAVENAME                    1049
#define IDC_BEEP                        1050
#define IDC_WAVE                        1051
#define IDC_BROWSE                      1052
#define IDC_UNDER                       1053
#define IDC_1H                          1054
#define IDC_30M                         1055
#define IDC_BROWSENOTIFY                1056
#define IDC_DEC                         1057
#define IDC_SMALLFONT                   1058
#define IDC_MIDFONT                     1059
#define IDC_BIGFONT                     1060
#define IDC_SMALLSIZE                   1061
#define IDC_MIDSIZE                     1062
#define IDC_BIGSIZE                     1063
#define IDC_COUNT                       1064
#define IDC_BROWSEEXEC                  1065
#define IDC_ALARMTIME                   1066
#define IDC_EXECNAME                    1067
#define IDC_VOLUME                      1068
#define IDC_CONFIRM                     1069
#define IDC_NOTIFYNAME                  1070
#define IDC_ALARMTITLE                  1071
#define IDC_5MIN                        1072
#define IDC_CUSTOM                      1073
#define IDC_SNOOZE                      1074
#define IDC_SYNC                        1075
#define IDC_FLOAT                       1076
#define IDC_GRAYBACK                    1077
#define IDC_PREVMONTH                   1078
#define IDC_PREVYEAR                    1079
#define IDC_NEXTMONTH                   1080
#define IDC_NEXTYEAR                    1081
#define IDC_NEXTWEEK                    1082
#define IDC_TODAY                       1083
#define IDC_PREVWEEK                    1084
#define IDC_DATEFORMAT                  1085
#define IDC_MULTI                       1086
#define IDC_AFTER                       1087
#define IDC_AFTERDATE                   1088
#define IDC_BEFORE                      1089
#define IDC_BEFOREDATE                  1090
#define IDC_FINDTEXT                    1091
#define IDC_FINDTITLE                   1092
#define IDC_FINDLOCATION                1093
#define IDC_FINDNOTE                    1094
#define IDC_FINDNEXT                    1095
#define IDC_TEST                        1096
#define IDC_DAYVIEW                     1097
#define IDC_GRAYVIEW                    1098
#define IDC_ESCNONE                     1099
#define IDC_ESCEXIT                     1100
#define IDC_ESCHIDE                     1101
#define IDC_RANGE                       1102
#define IDC_TODODAYDISP                 1103
#define IDC_TODOHALFDISP                1104
#define IDC_BOTH                        1105
#define IDC_MAIN                        1106
#define IDC_PRIVATE                     1107
#define IDC_TODOBOTH                    1108
#define IDC_TODO                        1109
#define IDC_APP                         1110
#define IDC_REV                         1111
#define IDC_TODOREV                     1112
#define IDC_RECV                        1113
#define IDC_SEND                        1114
#define IDC_BACKDEF                     1115
#define IDC_BACKRED                     1116
#define IDC_BACKGREEN                   1117
#define IDC_BACKBLUE                    1118
#define IDC_GRAYDEF                     1119
#define IDC_GRAYRED                     1120
#define IDC_GRAYGREEN                   1121
#define IDC_GRAYBLUE                    1122
#define IDC_TEXTDEF                     1123
#define IDC_TEXTRED                     1124
#define IDC_TEXTGREEN                   1125
#define IDC_TEXTBLUE                    1126
#define IDC_LINEDEF                     1127
#define IDC_LINERED                     1128
#define IDC_LINEGREEN                   1129
#define IDC_LINEBLUE                    1130
#define IDC_TODOSORT                    1131
#define IDC_POPUP                       1132
#define IDC_BUTTON1                     1137
#define IDM_BUTTON1                     32778	// [iwad]
#define IDM_BUTTON2                     32779	// [iwad]
#define IDM_FILE_NEW                    40001
#define IDM_FILE_OPEN                   40002
#define IDM_FILE_COPY                   40003
#define IDM_FILE_IMPORT                 40004
#define IDM_FILE_EXPORT                 40005
#define IDM_FILE_REMOVE                 40006
#define IDM_FILE_EXIT                   40007
#define IDM_EDIT_CUT                    40008
#define IDM_EDIT_COPY                   40009
#define IDM_EDIT_PASTE                  40010
#define IDM_HELP_TOPIC                  40011
#define IDM_HELP_ABOUT                  40012
#define IDM_EDIT_UNDO                   40013
#define IDM_VIEW_MINIMIZE               40014
#define IDM_VIEW_MONTH                  40015
#define IDM_VIEW_WEEK                   40016
#define IDM_VIEW_DAY                    40017
#define IDM_EDIT_DELETE                 40018
#define IDM_VIEW_HALFYEAR               40019
#define IDM_FILE_CLOSE                  40020
#define IDM_VIEW_INPUT                  40021
#define IDM_VIEW_OPTION                 40022
#define IDM_JUMP_DATE                   40023
#define IDM_JUMP_FIND                   40024
#define IDM_VIEW_TODO                   40025
#define IDM_VIEW_DIARY                  40026
#define IDM_VIEW_PRIVATE                40027
#define IDM_EDIT_FULL                   40028
#define IDM_EDIT_TODO                   40029
#define IDM_EDIT_ALT                    40030
#define IDM_FILE_WRITE                  40031
#define IDM_FILE_INSERT                 40032
#define IDM_FILE_SYNC                   40033

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        123
#define _APS_NEXT_COMMAND_VALUE         40034
#define _APS_NEXT_CONTROL_VALUE         1138
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
